name: Terraform Pipeline

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Code checkout
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false

      # Step 1: Secret se direct JSON file banana
      - name: Create credentials file
        run: |
          echo '${{ secrets.GCP_CREDENTIALS }}' > ${{ github.workspace }}/key.json

      - name: Set GCP Environment Variable
        run: |
          echo "GOOGLE_APPLICATION_CREDENTIALS=${{ github.workspace }}/key.json" >> $GITHUB_ENV

      # Step 3: Terraform Init
      - name: Terraform Init
        run: terraform init

      # Step 4: Terraform Plan
      - name: Terraform Plan
        run: terraform plan

      # Step 5: Terraform Apply
      - name: Terraform Apply
        run: terraform apply -auto-approve