# name: "Terraform Deployments"

# on:
#   push:
#     branches:
#       - main  

# jobs:
#   terraform:
#     name: "Terraform Job"
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout Code
#         uses: actions/checkout@v4

#       - name: Setup Terraform
#         uses: hashicorp/setup-terraform@v3

#       - name: Authenticate to Google Cloud
#         uses: google-github-actions/auth@v2
#         with:
#           credentials_json: ${{ secrets.GCP_SA_KEY }}

#       - name: Terraform Inita
#         run: terraform init

#       - name: Terraform Plan
#         run: terraform plan 

#       - name: Terraform Apply
#         run: terraform apply 



name: "Terraform Deployments"

on:
  push:
    branches:
      - main  

# WIF ke liye ye permissions lazmi hain
permissions:
  contents: read
  id-token: write 

jobs:
  terraform:
    name: "Terraform Job"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # Setup Terraform step ko auth se pehle ya baad mein rakh sakte hain
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          # Yahan Provider ka poora path dalein jo Step 4/5 mein copy kiya tha
          workload_identity_provider: 'projects/305318903527/locations/global/workloadIdentityPools/mouaz-pool/providers/github-provider'
          service_account: 'terraform@scrapemore.iam.gserviceaccount.com'

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan 

      # Apply ko auto-approve par rakhein warna pipeline hang ho jayegi
      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'
        run: terraform apply -auto-approve